In [1]:
import pickle
from keras.preprocessing.image import ImageDataGenerator

Using TensorFlow backend.


In [2]:
x=pickle.load(open('feature.pkl','rb'))

In [3]:
y=pickle.load(open('lebel.pkl','rb'))

In [4]:
x

array([[[[120,  28,   9],
         [122,  30,  11],
         [124,  32,  12],
         ...,
         [ 89,  19,   6],
         [ 90,  20,   7],
         [ 91,  21,   8]],

        [[124,  30,  11],
         [125,  31,  12],
         [127,  33,  14],
         ...,
         [ 92,  20,   8],
         [ 92,  20,   8],
         [ 93,  21,   9]],

        [[128,  33,  13],
         [129,  34,  15],
         [130,  35,  16],
         ...,
         [ 91,  17,   5],
         [ 92,  19,   6],
         [ 94,  20,   8]],

        ...,

        [[128, 144, 150],
         [133, 148, 156],
         [129, 144, 152],
         ...,
         [128, 141, 151],
         [102, 114, 123],
         [107, 119, 128]],

        [[122, 139, 142],
         [ 96, 112, 117],
         [101, 117, 124],
         ...,
         [131, 151, 162],
         [124, 142, 154],
         [106, 122, 131]],

        [[120, 135, 138],
         [ 76,  90,  96],
         [ 72,  85,  93],
         ...,
         [135, 151, 163],
        

In [5]:
x=x/255 #feature scaling for running model in a faster way

In [6]:
x

array([[[[0.47058824, 0.10980392, 0.03529412],
         [0.47843137, 0.11764706, 0.04313725],
         [0.48627451, 0.1254902 , 0.04705882],
         ...,
         [0.34901961, 0.0745098 , 0.02352941],
         [0.35294118, 0.07843137, 0.02745098],
         [0.35686275, 0.08235294, 0.03137255]],

        [[0.48627451, 0.11764706, 0.04313725],
         [0.49019608, 0.12156863, 0.04705882],
         [0.49803922, 0.12941176, 0.05490196],
         ...,
         [0.36078431, 0.07843137, 0.03137255],
         [0.36078431, 0.07843137, 0.03137255],
         [0.36470588, 0.08235294, 0.03529412]],

        [[0.50196078, 0.12941176, 0.05098039],
         [0.50588235, 0.13333333, 0.05882353],
         [0.50980392, 0.1372549 , 0.0627451 ],
         ...,
         [0.35686275, 0.06666667, 0.01960784],
         [0.36078431, 0.0745098 , 0.02352941],
         [0.36862745, 0.07843137, 0.03137255]],

        ...,

        [[0.50196078, 0.56470588, 0.58823529],
         [0.52156863, 0.58039216, 0.61176471]

In [7]:
x.shape

(66, 100, 100, 3)

In [8]:
#data augmentaion

In [9]:
dataGen = ImageDataGenerator(width_shift_range=0.1,
                             height_shift_range=0.1,
                             zoom_range=0.2,
                             shear_range=0.1,
                             rotation_range=20,
                             horizontal_flip= True)

In [10]:
pip install keras-tuner

Note: you may need to restart the kernel to use updated packages.


In [11]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
print(tf.__version__)
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout, Activation, Flatten, Conv2D, MaxPooling2D

2.1.0


In [12]:
x[0]

array([[[0.47058824, 0.10980392, 0.03529412],
        [0.47843137, 0.11764706, 0.04313725],
        [0.48627451, 0.1254902 , 0.04705882],
        ...,
        [0.34901961, 0.0745098 , 0.02352941],
        [0.35294118, 0.07843137, 0.02745098],
        [0.35686275, 0.08235294, 0.03137255]],

       [[0.48627451, 0.11764706, 0.04313725],
        [0.49019608, 0.12156863, 0.04705882],
        [0.49803922, 0.12941176, 0.05490196],
        ...,
        [0.36078431, 0.07843137, 0.03137255],
        [0.36078431, 0.07843137, 0.03137255],
        [0.36470588, 0.08235294, 0.03529412]],

       [[0.50196078, 0.12941176, 0.05098039],
        [0.50588235, 0.13333333, 0.05882353],
        [0.50980392, 0.1372549 , 0.0627451 ],
        ...,
        [0.35686275, 0.06666667, 0.01960784],
        [0.36078431, 0.0745098 , 0.02352941],
        [0.36862745, 0.07843137, 0.03137255]],

       ...,

       [[0.50196078, 0.56470588, 0.58823529],
        [0.52156863, 0.58039216, 0.61176471],
        [0.50588235, 0

In [13]:
x[0].shape

(100, 100, 3)

In [14]:
model= Sequential()
model.add(Conv2D(64, (3,3),input_shape=x.shape[1:], activation= 'relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())
model.add(Dense(128,input_shape=x.shape[1:], activation='relu'))

model.add(Dense(2,activation='softmax'))
          

In [15]:
model.compile(loss="sparse_categorical_crossentropy",
             optimizer ="adam",
             metrics =['accuracy'])


In [16]:
model.fit(x,y, epochs=20,validation_split=0.1)

Train on 59 samples, validate on 7 samples
Epoch 1/20
59/59 [==============================] - 3s 45ms/sample - loss: 2.6498 - accuracy: 0.6102 - val_loss: 0.6318 - val_accuracy: 0.7143
Epoch 2/20
59/59 [==============================] - 1s 18ms/sample - loss: 1.0064 - accuracy: 0.5424 - val_loss: 1.1632 - val_accuracy: 0.2857
Epoch 3/20
59/59 [==============================] - 1s 19ms/sample - loss: 0.9318 - accuracy: 0.3729 - val_loss: 0.7255 - val_accuracy: 0.2857
Epoch 4/20
59/59 [==============================] - 1s 19ms/sample - loss: 0.6896 - accuracy: 0.4407 - val_loss: 0.5469 - val_accuracy: 0.7143
Epoch 5/20
59/59 [==============================] - 1s 20ms/sample - loss: 0.6705 - accuracy: 0.6271 - val_loss: 0.5516 - val_accuracy: 0.7143
Epoch 6/20
59/59 [==============================] - 1s 19ms/sample - loss: 0.6235 - accuracy: 0.6271 - val_loss: 0.6110 - val_accuracy: 0.7143
Epoch 7/20
59/59 [==============================] - 1s 19ms/sample - loss: 0.6029 - accuracy: 0.644

In [28]:
model_name="cat_and_dog_own_data_four.h5"
model.save(model_name)

In [29]:
from tensorflow.keras.models import load_model
load_model(model_name)

In [38]:
from keras.preprocessing import image
import numpy as np

img_pred=image.load_img(r"C:\Users\Asus\own_dataset\dog\dog.7306.jpg",target_size=(100,100))

img_pred=image.img_to_array(img_pred)
img_pred=np.expand_dims(img_pred, axis=0)
rslt= model.predict(img_pred)

print(rslt)
if rslt[0][0]>rslt[0][1]:
    prediction="cat"
    
    
else:
    prediction="dog"
print(prediction)


[[0. 1.]]
dog


In [25]:
#checking my main model size


In [37]:
import os
def get_file_size(file_path):
    size= os.path.getsize(file_path)
    return size
def convert_bytes(size, unit=None):
    if unit== "KB":
        return print ('File size:' +str(round(size/1024,3)) +'kilobytes')
    elif unit=="MB":
         return print ('File size:' +str(round(size/(1024*1024),3)) +'Megabytes')
    else:
         return print ('File size:' +str(size) +'bytes')
convert_bytes(get_file_size(model_name),"MB")

File size:50.081Megabytes


In [40]:
tf_lite_model="second_tflite.tflite"

In [41]:
tf_lite_converter=tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model=tf_lite_converter.convert()

In [43]:
#save the model in memory



In [44]:
tflite_model_name= tf_lite_model
open(tflite_model_name, "wb").write(tflite_model)

17493072

In [45]:
convert_bytes(get_file_size(tf_lite_model),"MB")

File size:16.683Megabytes


In [46]:
#evaluate my tflite mode;

In [47]:
interpreter =tf.lite.Interpreter(model_path=tf_lite_model)
input_details=interpreter.get_input_details()
output_details=interpreter.get_output_details()
print("input shape:",input_details[0]['shape'])
print("input type:",input_details[0]['dtype'])
print("output shape:",output_details[0]['shape'])
print("output shape:",output_details[0]['dtype'])

input shape: [  1 100 100   3]
input type: <class 'numpy.float32'>
output shape: [1 2]
output shape: <class 'numpy.float32'>


In [ ]:
#making quantized model

In [58]:
tf_lite_model_quantized="second_quantized_tflite.tflite"

In [59]:
tf_lite_converter=tf.lite.TFLiteConverter.from_keras_model(model)

tf_lite_converter.optimizations=[tf.lite.Optimize.DEFAULT]
tf_lite_converter.target_spec.supported_types=[tf.float16]
tflite_model=tf_lite_converter.convert()

In [54]:
print (tf.__version__)

2.1.0


In [60]:
tflite_model_name= tf_lite_model_quantized
open(tflite_model_name, "wb").write(tflite_model)

8748700

In [61]:
convert_bytes(get_file_size(tf_lite_model_quantized),"MB")

File size:8.343Megabytes
